### ISSUE TITLE
Use encoding UTF-8

### ISSUE THREAD

**Issue by gerardbm** [bronger/pp3#1]
Hi, I would like to use the encoding UTF-8, because if I change some names, let's say "Andrómeda" this prints "AndrĀşmeda". Where should I search for a solution? LaTeX or cc files? Thanks in advance!

**Comment by bronger** [comment]
Note that PP3 is unmaintained and unsupported. I can only guess that it may be enough to put

    \usepackage[utf8]{inputenc}

in the preamble that you use in your .pp3 files.

**Comment by gerardbm** [comment]
That worked perfectly! Thanks!

It's an amazing software, because it works in Debian 9 with the recent versions of Latex and dvips.
